In [1]:
import numpy as np

## Descomposición de matrices

Descomponer una matrzi consiste en encontrar 2 o mas matrices que puedan representar mi matriz original y tengan ciertas propiedades.

![alt](./descomposicion_matrices.jpg)

$$
\lambda_i = autovalores_i
$$

### Notas

**Descomponer una matriz:** Quiere decir encontrar dos o más matrices que me ayuden a escribir la matriz original y que tengan ciertas propiedades.

Una matriz A la podemos escribir como: sus autovectores producto punto una matriz diagonal, donde la matriz diagonal tiene todos los autovalores encontrados, producto punto la matriz inversa de sus autovectores.

- A_calc = autovectores.dot(np.diag(autovalores)).dot(np.linalg.inv(autovectores))

**Descomposición 2:** Restricciones:Nuestra Matriz A sea real y simétrica (A = A-transpuesta).

Decimos que A = la matriz de autovectores producto punto la matriz diagonal con los autovalores, producto punto la transpuesta de la matriz de autovectores. NOTA: Calcular la transpuesta de una matriz es mucho más económico en cómputo que calcular la inversa de una matriz. Y hay que recordar que el cómputo cuesta dinero.
- A_calc = autovectores.dot(np.diag(autovalores)).dot(autovectores.T)

In [27]:
A = np.array([[3.,2.], [4.,1.]])
print(A)

[[3. 2.]
 [4. 1.]]


In [21]:
autovalores ,autovectores = np.linalg.eig(A)
print(autovalores)
print(autovectores)


[ 5. -1.]
[[ 0.70710678 -0.4472136 ]
 [ 0.70710678  0.89442719]]


In [22]:
np.diag(autovalores)


array([[ 5.,  0.],
       [ 0., -1.]])

In [23]:
np.linalg.inv(autovectores)


array([[ 0.94280904,  0.47140452],
       [-0.74535599,  0.74535599]])

In [28]:
A_calc = (autovectores
          .dot(np.diag(autovalores))
          .dot(np.linalg.inv(autovectores)))
A_calc

array([[3., 2.],
       [4., 1.]])

In [32]:
B = np.array([[3,2], [2,3]])
B

array([[3, 2],
       [2, 3]])

In [33]:
print(B == B.T)

[[ True  True]
 [ True  True]]


Si la matriz es simetrica la descomposicion se puede representar como:

$$
A = [autovectores] * diagonal(\lambda) * [autovectores]^T
$$

In [34]:
autovalores ,autovectores = np.linalg.eig(B)
print(autovalores)
print(autovectores)

[5. 1.]
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [35]:
B_calc = (autovectores
          .dot(np.diag(autovalores))
          .dot(autovectores.T))
B_calc

array([[3., 2.],
       [2., 3.]])

Cuando una matriz es cuadrada la podemos escribir en funcion de los autovectores y autovalores

y en caso de ser simetrica podemos usar la traspuesta en lugar de la inversa.