In [1]:
import numpy as np

**Descomponer una matriz:** Quiere decir encontrar dos o más matrices que me ayuden a escribir la matriz original y que tengan ciertas propiedades.

Una matriz A la podemos escribir como: sus autovectores producto punto una matriz diagonal, donde la matriz diagonal tiene todos los autovalores encontrados, producto punto la matriz inversa de sus autovectores.

- A_calc = autovectores.dot(np.diag(autovalores)).dot(np.linalg.inv(autovectores))

**Descomposición 2:** Restricciones:Nuestra Matriz A sea real y simétrica (A = A-transpuesta).

Decimos que A = la matriz de autovectores producto punto la matriz diagonal con los autovalores, producto punto la transpuesta de la matriz de autovectores. NOTA: Calcular la transpuesta de una matriz es mucho más económico en cómputo que calcular la inversa de una matriz. Y hay que recordar que el cómputo cuesta dinero.
- A_calc = autovectores.dot(np.diag(autovalores)).dot(autovectores.T)

In [2]:
A = np.array([[3,2], [4,1]])
print(A)

[[3 2]
 [4 1]]


In [5]:
autovalores ,autovectores = np.linalg.eig(A)


In [6]:
print(autovalores)
print(autovectores)

[ 5. -1.]
[[ 0.70710678 -0.4472136 ]
 [ 0.70710678  0.89442719]]


In [7]:
A_calc = (autovectores
          .dot(np.diag(autovalores))
          .dot(np.linalg.inv(autovectores)))
A_calc

array([[3., 2.],
       [4., 1.]])

In [14]:
A = np.array([[3,2], [2,3]])
A

array([[3, 2],
       [2, 3]])

In [9]:
print(A == A.T)

[[ True  True]
 [ True  True]]


In [10]:
autovalores ,autovectores = np.linalg.eig(A)
print(autovalores)
print(autovectores)

[5. 1.]
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [16]:
A_calc = (autovectores
          .dot(np.diag(autovalores))
          .dot(autovectores.T))
A_calc

array([[3., 2.],
       [2., 3.]])

In [20]:
A_calc == A

array([[False, False],
       [False, False]])

Cuando una matriz es cuadrada la podemos escribir en funcion de los autovectores y autovalores

y en caso de ser simetrica podemos usar la traspuesta en lugar de la inversa.