# ¿Cómo descompongo una matriz no cuadrada (SVD)?

In [2]:
import numpy as np



Una matriz ortogonal es donde todos sus vectores son ortonormales
Dadas 3 matrices U, V y D
dondes U y V son matrices ortogonales y D es diagonal
y estan compuestas por
- U → vectores izquierdos singulares
- V → vectores derechos singulares
- D → matriz diagonal de valores singulares


Descomposición de una matriz en valores singulares
La descomposición por autovectores sólo es aplicable a matrices cuadradas. El presente método permite descomponer cualquier matriz en tres matrices:

- U → vectores izquierdos singulares
- D → matriz diagonal de valores singulares
- V → vectores derechos singulares

In [3]:
A = np.array([[1.,2.,3.],[3.,4.,5.]])
A


array([[1., 2., 3.],
       [3., 4., 5.]])

In [4]:
U, D, V = np.linalg.svd(A)

In [5]:
print(U)

[[-0.46410668  0.88577931]
 [-0.88577931 -0.46410668]]


In [6]:
# D retorna la diagonal en forma de vector
print(D)

[7.97638869 0.61418515]


In [14]:
V.shape

(3, 3)

In [7]:
# para ver la matriz diagonal debemos procesarla
print(np.diag(D))

[[7.97638869 0.        ]
 [0.         0.61418515]]


In [8]:
print(V)

[[-0.39133557 -0.5605708  -0.72980603]
 [ 0.8247362   0.13817999 -0.54837623]
 [ 0.40824829 -0.81649658  0.40824829]]


In [46]:
# A sera igual al producto punto de todas las matrices resultantes de svd
# A = U * D * V
D_matriz = np.diag(D)
print(D_matriz)

# se le agrega otra columna para que coincida con la dimension de V
D_matriz = np.append(D_matriz, [[0], [0]], axis=1)

print(D_matriz)


[[7.97638869 0.        ]
 [0.         0.61418515]]
[[7.97638869 0.         0.        ]
 [0.         0.61418515 0.        ]]


In [34]:
A_calc = U.dot(D_matriz).dot(V)
# Se comprueba la combercion de matrices
A_calc


array([[1., 2., 3.],
       [3., 4., 5.]])

In [29]:
A.shape == A_calc.shape

True

In [43]:
A == A_calc

array([[False, False, False],
       [False, False, False]])

In [31]:
A[0][0] == A_calc[0][0]

False

In [45]:
print(A[0][0])
print(A_calc[0][0])


1.0
0.9999999999999998


vemos que lo valores no son iguales ya que python esta trabajando con N decimales para aproximar el valor

In [37]:
A_calc.astype(int)


array([[0, 1, 2],
       [2, 3, 4]])

In [38]:
np.int_(A_calc)

array([[0, 1, 2],
       [2, 3, 4]])

In [41]:
np.around(A_calc)

array([[1., 2., 3.],
       [3., 4., 5.]])

In [42]:
np.around(A_calc) == A

array([[ True,  True,  True],
       [ True,  True,  True]])