# ¿Qué es una pseudo inversa de Moore Penrose y cómo calcularla?

Un sistema de ecuaciones lineales se puede representar como

$$
Ax = b
$$

y si existe $A^-1$ la solucion del sistema se puede representar como:

$$
\exists A^-1 \Rightarrow x = A^-1 b
$$

pero en caso de que $A$ sea singular, la pseudo inversa de $A$ se puede representar como:

$$
A * A_pse \approx Id
$$

Donde $Id$ es la identidad de $A$ y $A_pse$ es la pseudo inversa de $A$.

La pseudo inversa de Moore Penrose es una aplicación directa de SVD, que nos permite resolver en determinados momentos sistemas de ecuaciones lineales con múltiples soluciones. Es utilizada cuando en un sistema de ecuaciones lineales representado por Ax = B, x no tiene inversa. Esta operación es única y existe si se verifican 4 condiciones.

![Pseudo inversa](./pseudo_inversa.png)

### Cómo calcular la pseudo inversa de Moore Penrose

Para calcularla se siguen los siguientes pasos:

- Calcular las matrices U, D, y V (matrices SVD) de A.
- Construir D_pse: una matriz de ceros que tiene igual dimension de A, y que luego se transpone.
- Reemplazar la submatriz D_pse[: D.shape[0], : D.shape[0]] por np.linalg.inv(np.diag(D))
- Reconstruir pseudoinversa: A_pse = V.T.dot(D_pse).dot(U.T)

### Cómo calcular la pseudo inversa de Moore Penrose en Python

Para calcularla automaticamente por Python: `np.linalg.pinv(A)`

Lo que obtenemos con A_pse es una matriz muy cercana a la inversa. Cercano en el sentido de que minimiza la norma dos de estas distancias. O sea, de estos errores que estamos cometiendo.

A_pse no es conmutativa, es decir, A_pse·A ≠ A·A_pse

In [1]:
import numpy as np

# que al hacer nos muestre los numeros muy cercanos a 0 como 0
np.set_printoptions(suppress=True)

In [2]:
A = np.array([[2, 3], [5, 7], [11, 13]])
print(A)

[[ 2  3]
 [ 5  7]
 [11 13]]


In [3]:
U, D, V = np.linalg.svd(A)
print("U")
print(U)
print("D")
print(D)
print("V")
print(V)

U
[[-0.18499741 -0.47276624 -0.86154979]
 [-0.44249308 -0.74271297  0.50257071]
 [-0.87748267  0.4742041  -0.07179582]]
D
[19.40321383  0.71783924]
V
[[-0.63055377 -0.77614557]
 [ 0.77614557 -0.63055377]]


In [4]:
D_pse = np.zeros((A.shape[0], A.shape[1])).T
print(D_pse)

[[0. 0. 0.]
 [0. 0. 0.]]


In [5]:
print("Valores a reemplazar en D_pse")
print(D_pse[:D.shape[0], :D.shape[0]])

Valores a reemplazar en D_pse
[[0. 0.]
 [0. 0.]]


In [6]:
print("Valores que pondremos en D_pse")
print(np.linalg.inv(np.diag(D)))

Valores que pondremos en D_pse
[[0.05153785 0.        ]
 [0.         1.39306957]]


In [8]:
print("D_pse")
D_pse[:D.shape[0], :D.shape[0]] = np.linalg.inv(np.diag(D))
print(D_pse)

D_pse
[[0.05153785 0.         0.        ]
 [0.         1.39306957 0.        ]]


In [9]:
A_pse = V.T.dot(D_pse).dot(U.T)
print(A_pse)

[[-0.50515464 -0.78865979  0.54123711]
 [ 0.42268041  0.67010309 -0.3814433 ]]


In [11]:
A_pse_calc = np.linalg.pinv(A)
print(A_pse_calc)

[[-0.50515464 -0.78865979  0.54123711]
 [ 0.42268041  0.67010309 -0.3814433 ]]


In [12]:
print(A_pse.dot(A))

[[ 1. -0.]
 [ 0.  1.]]


In [13]:
np.set_printoptions(suppress = False)

In [14]:
print(A_pse.dot(A))

[[ 1.00000000e+00 -8.88178420e-16]
 [ 2.66453526e-15  1.00000000e+00]]


In [15]:
print(A.dot(A_pse))

[[ 0.25773196  0.43298969 -0.06185567]
 [ 0.43298969  0.74742268  0.03608247]
 [-0.06185567  0.03608247  0.99484536]]


In [16]:
A_pse_2 = np.linalg.inv(A.T.dot(A)).dot(A.T)
print(A_pse_2)

[[-0.50515464 -0.78865979  0.54123711]
 [ 0.42268041  0.67010309 -0.3814433 ]]


In [17]:
print(A_pse)

[[-0.50515464 -0.78865979  0.54123711]
 [ 0.42268041  0.67010309 -0.3814433 ]]
