# ¿Qué es una pseudo inversa de Moore Penrose y cómo calcularla?

Un sistema de ecuaciones lineales se puede representar como

$$
Ax = b
$$

y si existe $A^{-1}$ la solucion del sistema se puede representar como:

$$
\exists A^{-1} \Rightarrow x = A^{-1} b
$$

pero en caso de que $A$ sea singular, la pseudo inversa de $A$ ($A_{pse}$) se puede representar como:

$$
A * A_{pse}\approx Id
$$

Donde $Id$ es la identidad de $A$ y $A_pse$ es la pseudo inversa de $A$.

Dice que

V obtenida de la descomposicion SVD

$A_pse = V * D_{pse} * U^t$


La pseudo inversa de Moore Penrose es una aplicación directa de SVD, que nos permite resolver en determinados momentos sistemas de ecuaciones lineales con múltiples soluciones.

Es utilizada cuando en un sistema de ecuaciones lineales representado por Ax = B, x no tiene inversa. Esta operación es única y existe si se verifican 4 condiciones:

![Pseudo inversa](./pseudo_inversa.png)

### Cómo calcular la pseudo inversa de Moore Penrose

Para calcularla se siguen los siguientes pasos:

- Calcular las matrices U, D, y V (matrices SVD) de A.
- Construir D_pse: una matriz de ceros que tiene igual dimension de A, y que luego se transpone.
- Reemplazar la submatriz D_pse[: D.shape[0], : D.shape[0]] por np.linalg.inv(np.diag(D))
- Reconstruir pseudoinversa: A_pse = V.T.dot(D_pse).dot(U.T)

### Cómo calcular la pseudo inversa de Moore Penrose en Python

Para calcularla automaticamente por Python: `np.linalg.pinv(A)`

Lo que obtenemos con A_pse es una matriz muy cercana a la inversa. Cercano en el sentido de que minimiza la norma dos de estas distancias. O sea, de estos errores que estamos cometiendo.

A_pse no es conmutativa, es decir, A_pse·A ≠ A·A_pse

In [1]:
import numpy as np

# que al hacer nos muestre los numeros muy cercanos a 0 como 0
np.set_printoptions(suppress=True)

In [4]:
A = np.array([[2,3], [5,7], [11,13]])
A


array([[ 2,  3],
       [ 5,  7],
       [11, 13]])

Cuando la pseudo inversa de Moore Penrose, verifica 4 condiciones, en donde la matriz existe y es unica.

In [7]:
U, D, V = np.linalg.svd(A)
print("U")
print(U)
print("D")
print(D)
print("V")
print(V)


U
[[-0.18499741 -0.47276624 -0.86154979]
 [-0.44249308 -0.74271297  0.50257071]
 [-0.87748267  0.4742041  -0.07179582]]
D
[19.40321383  0.71783924]
V
[[-0.63055377 -0.77614557]
 [ 0.77614557 -0.63055377]]


In [10]:
D_pse = np.zeros(A.shape).T
D_pse


array([[0., 0., 0.],
       [0., 0., 0.]])

Calcular el reciproco de la matriz

In [11]:
print("Valores a reemplazar en D_pse")
print(D_pse[:D.shape[0], :D.shape[0]])

Valores a reemplazar en D_pse
[[0. 0.]
 [0. 0.]]


In [13]:
print("Valores que usaremos en D_pse")
print(np.linalg.inv(np.diag(D)))

Valores que usaremos en D_pse
[[0.05153785 0.        ]
 [0.         1.39306957]]


In [14]:
print("D_pse")
D_pse[:D.shape[0], :D.shape[0]] = np.linalg.inv(np.diag(D))
D_pse


D_pse


array([[0.05153785, 0.        , 0.        ],
       [0.        , 1.39306957, 0.        ]])

In [15]:
A_pse = V.T.dot(D_pse).dot(U.T)
# matriz que puede o no ser una pseudoinversa de A
A_pse

array([[-0.50515464, -0.78865979,  0.54123711],
       [ 0.42268041,  0.67010309, -0.3814433 ]])

In [16]:
A

array([[ 2,  3],
       [ 5,  7],
       [11, 13]])

In [18]:
A_pse_calc = np.linalg.pinv(A)
A_pse_calc


array([[-0.50515464, -0.78865979,  0.54123711],
       [ 0.42268041,  0.67010309, -0.3814433 ]])

In [19]:
A_pse_calc == A_pse

array([[ True,  True,  True],
       [ True, False,  True]])

In [20]:
A_pse.dot(A)

array([[ 1., -0.],
       [ 0.,  1.]])

In [23]:
np.set_printoptions(suppress=False)
A_pse.dot(A)


array([[ 1.00000000e+00, -8.88178420e-16],
       [ 2.66453526e-15,  1.00000000e+00]])

In [25]:
# la pseudoinversa no obtiene la indentidad al multiplicar por la izquierda y por la derecha, solo en una direccion se aproxima a la identidad, NO ES CONMUTATIVA
A.dot(A_pse)

array([[ 0.25773196,  0.43298969, -0.06185567],
       [ 0.43298969,  0.74742268,  0.03608247],
       [-0.06185567,  0.03608247,  0.99484536]])

Hay otros tipos de pseudoinversa

In [28]:
A_pse_2 = np.linalg.inv(A.T.dot(A)).dot(A.T)
print("A_pse_2")
print(A_pse_2)
print("A_pse")
print(A_pse)


A_pse_2
[[-0.50515464 -0.78865979  0.54123711]
 [ 0.42268041  0.67010309 -0.3814433 ]]
A_pse
[[-0.50515464 -0.78865979  0.54123711]
 [ 0.42268041  0.67010309 -0.3814433 ]]


Si bien son iguales la que esta implementada en python es la que utiliza el metodo SVD ya que es mas certera y computacionalmente mas efectiva ya que posee un menor margen de error.

### Resumen Alumnos

- La pseudo inversa de Moore Penrose es utilizada cuando en un sistema de ecuaciones lineales representado por $Ax = B$, $x$ no tiene inversa.
- La pseudo inversa de MP es única y existe si se verifican 4 condiciones.
- Para calcularla se siguen los siguientes pasos:
  1. Calcular las matrices U, D, y V (matrices SVD) de A.
  2. Construir D_pse: una matriz de ceros que tiene igual dimension de A, y que luego se transpone.
  3. Reemplazar la submatriz `D_pse[: D.shape[0], : D.shape[0]]` por np.linalg.inv(np.diag(D))
  4. Reconstruir pseudoinversa: `A_pse = V.T.dot(D_pse).dot(U.T)`

**Notas**

- Para calcularla automaticamente por Python: `np.linalg.pinv(A)`
- Lo que obtenemos con A_pse es una matriz muy cercana a la inversa. Cercano en el sentido de que minimiza la norma dos de estas distancias. O sea, de estos errores que estamos cometiendo.
- A_pse no es conmutativa, es decir, A_pse·A ≠ A·A_pse

## Ejercicio

¿Cuál es la pseudoinversa de Moore Penrose de la matriz?
[[1 2]
[3 4]
[5 6]]

In [7]:
A = np.array([[1,2], [3,4], [5,6]])
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [10]:
# pseudoinversa de Moore Penrose
A_pse = np.linalg.pinv(A)
A_pse


array([[-1.33333333, -0.33333333,  0.66666667],
       [ 1.08333333,  0.33333333, -0.41666667]])

Ahora validando por el metodo largo de SVD

In [9]:
U, D, V = np.linalg.svd(A)
print("U")
print(U)
print("D")
print(D)
print("V")
print(V)


U
[[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]
D
[9.52551809 0.51430058]
V
[[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]
